apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: staticpages.kubernetes.chinzzii.com
spec:
  group: kubernetes.chinzzii.com
  names:
    kind: StaticPage
    singular: staticpage
    plural: staticpages
    shortNames:
      - sp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                contents:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
